"""add_price_cost_quantity_history_to_products

Revision ID: 8806c30ab0f2
Revises: 34a2c03e1fb7
Create Date: 2026-03-30 05:11:55.430007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8806c30ab0f2'
down_revision: Union[str, Sequence[str], None] = '34a2c03e1fb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_cost', sa.Numeric(), nullable=False))
    op.add_column('products', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('products', sa.Column('history', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('products', 'price')
    op.drop_column('products', 'quantity_in_stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('quantity_in_stock', sa.INTEGER(), nullable=False))
    op.add_column('products', sa.Column('price', sa.NUMERIC(), nullable=False))
    op.drop_column('products', 'history')
    op.drop_column('products', 'quantity')
    op.drop_column('products', 'price_cost')
    # ### end Alembic commands ###
